// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Export file: ../Assets/Scripts/behaviac/exported/behaviac_generated/behaviors/generated_behaviors.cs
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

namespace behaviac
{
	// Source file: HoverBotBT

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_HoverBotBT_node1 : behaviac.Action
	{
		public Action_bt_HoverBotBT_node1()
		{
			this.m_resultOption = EBTStatus.BT_INVALID;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.EBTStatus result = ((HoverBotAgent)pAgent).DoPatrol();
			return result;
		}
	}

	public static class bt_HoverBotBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("HoverBotBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("HoverBotAgent");
#endif
			// children
			{
				Selector node0 = new Selector();
				node0.SetClassNameString("Selector");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("HoverBotAgent");
#endif
				bt.AddChild(node0);
				{
					Action_bt_HoverBotBT_node1 node1 = new Action_bt_HoverBotBT_node1();
					node1.SetClassNameString("Action");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("HoverBotAgent");
#endif
					node0.AddChild(node1);
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

}
